export default {
  UPDATE_TASK_UNDER_EDIT: "UPDATE_TASK_UNDER_EDIT",
  SAVING_TASK_UNDER_EDIT: "SAVING_TASK_UNDER_EDIT",
  TASK_UNDER_EDIT_SAVED: "TASK_UNDER_EDIT_SAVED",

  REQUEST_TASKS: "REQUEST_TASKS",
  RECEIVE_TASKS: "RECEIVE_TASKS",

  ON_ERROR_MESSAGE: "ON_ERROR_MESSAGE",
  ON_REMOVE_MESSAGE: "ON_REMOVE_MESSAGE",

  SHOW_MAIN: "SHOW_MAIN",
  SHOW_EDIT: "SHOW_EDIT",

  RECEIVE_TASK_UNDER_EDIT: "RECEIVE_TASK_UNDER_EDIT"
}
